name: documentation

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: Source
      - uses: actions/checkout@v2
        with:
          repository: qnimble/quarto-examples
          path: MyExamples
          ref: main
          ssh-key: ${{secrets.SSH_DEPLOY_KEY}}
      - name: push to examples
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: main
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          echo "Got here"
          ls
          echo "Got here 32"
          ls ~
          echo "Got here 44"
          ls MyExamples
          echo "Got here 55"
          echo ls ${{env.GITHUB_WORKSPACE}}
          #git clone git@github.com:qnimble/quarto-examples.git /tmp/examples
          #cd /tmp/examples
          echo cd ${{env.GITHUB_WORKSPACE}}/Source
          cd Source
          echo "After CD"
          find -maxdepth 3  -mindepth 3 -type d -path '*examples*' -execdir mv '{}' ../ \;           
          rm LICENSE
          echo cp -ra * ../MyExamples
          cp -ra * ../MyExamples
          cd ../MyExamples
          pwd
          ls
          git status
          git add -u
          echo "did add"
          git status
          git commit -m "Autocommit"
          git push
          
              
