name: documentation

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: qnimble/quarto-examples
          path: /tmp/examples
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DEPLOYMENT_BRANCH: main
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: push to examples
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: main
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          #git clone git@github.com:qnimble/quarto-examples.git /tmp/examples
          cd /tmp/examples
          find -maxdepth 3  -mindepth 3 -type d -path '*examples*' -execdir mv '{}' ../ \;           
          rm LICENSE
          cp -ra * /tmp/examples
          cd /tmp/examples
          git add -u
          git commit -m "Autocommit"
          git push
          
              
